version: '2'
services:
    db:
        image: postgres
        volumes:
            - ~/sites/server-dockerfile/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    api-server:
        image: busybox
        volumes:
            d:/github/douban-girls/server-dockerfile/production:/go
        command: /go/api-server-exec
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
            - backend
        links:
            - redis
            - db
            - backend
    backend:
        image: busybox
        volumes:
            d:/github/douban-girls/server-dockerfile/production:/go
        command: /go/backend-exec
        depends_on:
            - redis
            - db
        links:
            - redis
            - db

    revel:
        image: annatarhe/revel:v0.0.4
        volumes:
            - ~/sites/server-dockerfile/production:/go
        command: ./run.sh
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
        links:
            - db
            - redis
    pro-crawler:
        image: golang:1.8.3
        volumes:
            - ~/code/douban-girls/server-dockerfile/crawler:/tmp
        # the build file must be named as `go-crawler`
        command: ./tmp/go-crawler
        links:
            - db
    dev-crawler:
        image: golang:1.8.3
        volumes:
            - ~/code/golang/src:/go/src
        # the build file must be named as `go-crawler`
        command: go run /go/src/github.com/douban-girls/crawler/main.go
        depends_on:
            - db
        links:
            - db
    crawler-py:
        image: annatarhe/scrapy:v0.1
        volumes:
            - d:/github/douban-girls/crawler:/py
        command: scrapy crawl dbmeinv
        links:
            - redis
            - db
        depends_on:
            - redis
            - db
