version: '2'
services:
    db:
        image: postgres
        volumes:
            - ~/Code/server-dockerfile/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    api-server:
        image: busybox
        volumes:
            d:/github/douban-girls/server-dockerfile/production:/go
        command: /go/api-server-exec
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
            - backend
        links:
            - redis
            - db
            - backend
    backend:
        image: busybox
        volumes:
            - ~/code/golang/src:/go/src
        command: /go/backend-exec
        depends_on:
            - redis
            - db
        links:
            - redis
            - db
        depends_on:
            - redis
            - db
