version: '2'
services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    node:
        image: node:latest
        ports:
            - "9000:9000"
        volumes:
            - d:/github/douban-girls/server:/usr/src/app
        depends_on:
            - redis
            - db
        working_dir: /usr/src/app
        command: npm run dev
    revel:
        image: annatarhe/revel:v0.0.4
        volumes:
            - d:/github/golang/src:/go/src
        command: revel run github.com/douban-girls/douban-girls-server
        environment:
            - GOROOT_BOOTSTRAP=/usr/local/go
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
        links:
            - db
            - redis
    pro-crawler:
        image: golang:1.8.3
        volumes:
            - d:/github/golang/src:/tmp
        # the build file must be named as `go-crawler`
        command: ./tmp/go-crawler
        links:
            - db
    dev-crawler:
        image: golang:1.8.3
        volumes:
            - d:/github/golang/src:/go/src
        command: go run /go/src/github.com/douban-girls/crawler/main.go
        depends_on:
            - db
        links:
            - db

#  NTFS in windows
#  https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5?u=friism
volumes:
    pgdata:
        external: true

