version: '2'
services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    api-server:
        image: busybox
        volumes:
            d:/github/douban-girls/server-dockerfile/production:/go
        command: /go/api-server-exec
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
            - backend
        links:
            - redis
            - db
            - backend
    backend:
        image: busybox
        volumes:
            d:/github/douban-girls/server-dockerfile/production:/go
        command: /go/backend-exec
        depends_on:
            - redis
            - db
        links:
            - redis
            - db

    crawler-py:
        image: annatarhe/scrapy:v0.4
        volumes:
            - d:/github/douban-girls/crawler:/py
        command: scrapy crawl dbmeinv
        links:
            - redis
            - db
        depends_on:
            - redis
            - db

#  NTFS in windows
#  https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5?u=friism
volumes:
    pgdata:
        external: true

