version: '2'
services:
    db:
        image: postgres
        volumes:
            - ~/code/douban-girls/server-dockerfile/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    revel:
        image: annatarhe/revel:v0.0.4
        volumes:
            - ~/code/golang/src:/go/src
        command: revel run github.com/douban-girls/douban-girls-server
        ports:
            - "9000:9000"
        depends_on:
            - redis
            - db
        links:
            - db
            - redis
    pro-crawler:
        image: golang:1.8.3
        volumes:
            - ~/code/douban-girls/server-dockerfile/crawler:/tmp
        # the build file must be named as `go-crawler`
        command: ./tmp/go-crawler
        links:
            - db
    dev-crawler:
        image: golang:1.8.3
        volumes:
            - ~/code/golang/src:/go/src
        # the build file must be named as `go-crawler`
        command: go run /go/src/github.com/douban-girls/crawler/main.go
        depends_on:
            - db
        links:
            - db
