apiVersion: v1
kind: Service
metadata:
  name: athena-server
  labels:
    name: athena
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  ports:
    - name: api-server-port
      protocol: TCP
      port: 8899
      targetPort: 8899
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432

